make:
	cd ~/newfolder/Clang/output/ && gcc ~/newfolder/Clang/prog1.c -o prog1 && ./prog1 | lolcat
prog3:
	cd ~/newfolder/Clang/output/ && gcc ~/newfolder/Clang/prog3.c -o prog3 && ./prog3 | lolcat
prog4:
	cd ~/newfolder/Clang/output/ && gcc ~/newfolder/Clang/prog4.c -o prog4 && ./prog4 | lolcat

prog5:
	cd ~/newfolder/Clang/output/ && gcc ~/newfolder/Clang/prog5.c -o prog5 && ./prog5 
	
prog6:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/prog6.c -o prog6 && ./prog6 

prog7:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/prog7.c -o prog7 && ./prog7 && sleep 1 && sl | lolcat 

prog8:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/prog8.c -o prog8 && ./prog8 && sleep 1 && sl | lolcat 

prog9:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/prog9.c -o prog9 && ./prog9 

prog10:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/prog10.c -o prog10 && ./prog10 

prog11:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/prog11.c -o prog11 && ./prog11 

prog12:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/prog12.c -o prog12 && ./prog12 

prog13:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/prog13.c -o prog13 && ./prog13 
prog14:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/prog14.c -o prog14 && ./prog14 
prog15:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/prog15.c -o prog15 && ./prog15 
p1:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p1.cpp -o p1 && ./p1 | pv -qL 40 | lolcat && sleep 1 && asciiquarium
p2:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p2.cpp -o p2 && ./p2 | pv -qL 40 | lolcat 
p3:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p3.cpp -o p3 && ./p3 | pv -qL 40 | lolcat 

p4:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p4.cpp -o p4 && ./p4 | pv -qL 40 | lolcat 
p5:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p5.cpp -o p5 && ./p5 | pv -qL 40 | lolcat 
p6:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p6.cpp -o p6 && ./p6 | pv -qL 40 | lolcat 
p7:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p7.cpp -o p7 && ./p7 | pv -qL 40 | lolcat 
p8:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p8.cpp -o p8 && ./p8 | pv -qL 40 | lolcat 
p9:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p9.cpp -o p9 && ./p9 | pv -qL 40 | lolcat 
p10:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p10.cpp -o p10 && ./p10 | lolcat 
p12:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p12.cpp -o p12 && ./p12 | lolcat 
p11:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p11.cpp -o p11 && ./p11 | lolcat 
p13:
	cd ~/mycode/Clang/output/ && g++ ~/mycode/Clang/cpp/p13.cpp -o p13 && ./p13 | lolcat 
al1:
	cd ~/mycode/Clang/output/ && gcc ~/mycode/Clang/dsa/al1.c -o al1 && ./al1 | pv -qL 40 | lolcat 
